services:
  app:
    build: .
    volumes:
      - .:/code
    ports:
      - 8000:8000
    env_file:
      - ./env_files/local.env
    command: python /code/manage.py runserver 0.0.0.0:8000
    depends_on:
      - db

  db:
    image: postgres
    env_file:
      - ./env_files/local.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
