services:
  app:
    build: .
    volumes:
      - .:/code
    ports:
      - 8000:8000
    command:
      - "python manage.py runserver -b 0.0.0.0:8000"
    depends_on:
      - db

  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
